### PR TITLE
Chores/travis

### LINKED ISSUE #5: Set up CI/CD
Connect travis, add `prepush` script which will run `prettier` and `eslint`

### PR DESCRIPTION
**Pull request by OleksiyRudenko**
Have it tested on my fork. Has built and published on [GitHub pages](https://oleksiyrudenko.github.io/tmbd-web-client/) successfully.

Please, follow guidelines from `TRAVIS.md` to set up GitHub/Travis token etc.

When merged to master should build and publish, making the app available at https://zonzujiro.github.io/tmbd-web-client/ (consider adding this link to project settings).

Resolves #5

### CODE REVIEW

**Comment by zonzujiro** [comment]
Can you set up `travis` for this repo too?

**Comment by OleksiyRudenko** [comment]
Unfortunately only repo admin can enable a repo on Travis. Not sure if you can grant me admin powers on public repo. Have done an experiment: invited you to collaborate on my fork, it didn't offer to grant you any special powers (beside push access)... Googled a bit, seems like some efforts from repo admin are unavoidable.

**Comment by OleksiyRudenko** [comment]
Another option is to create an organization, transfer this repo to the organization, grant some members owner role so they can act as admins. Still efforts from repo owner/admin are unavoidable.

**Comment by zonzujiro** [comment]
🤔  I can add travis integration, but I am not sure will have access to pipelines. Let's try

**Comment by zonzujiro** [comment]
Ok, it is done now. I will close this PR because we don't need it.

**Review by zonzujiro — APPROVED** [review]

**Pull request merged**
